### ISSUE TITLE
Ambiguous Unions in JSON output?

### ISSUE THREAD

**Issue by sordina** [dhall-lang/dhall-json#10]
I could be wrong, but are the JSON representation of unions ambiguous?

Example:

```
~/temp/dhall-examples
$ cat type3.dhall
[ < Left = +1 | Right : Bool | Other : Natural >
, < Other = +3 | Right : Bool | Left : Natural >
] : List < Left : Natural | Right : Bool | Other : Natural >

~/temp/dhall-examples
$ dhall-to-json < type3.dhall
[1,3]
```

**Comment by sordina** [comment]
Oops I accidentally closed the issue! Sorry!

**Comment by Gabriel439** [comment]
This is intentional.  See:

https://github.com/dhall-lang/dhall-json/issues/2

... and:

https://github.com/dhall-lang/dhall-lang/wiki/Getting-started%3A-Generate-JSON-or-YAML#unions

**Comment by sordina** [comment]
Ah interesting, it certainly makes sense for flexibly generating JSON, but what about the other direction? Say I wanted to interpret some Dhall generated JSON with Haskell, is the idea that you would explicitly create a 'tagged' output representation if the output could be ambiguous?

**Comment by Gabriel439** [comment]
So I don't have plans to convert in the other direction, but if I did I would most likely be strict in the conversion and reject weakly typed JSON

**Comment by sordina** [comment]
Thanks for the insight, I'll close the issue :)

**Comment by Gabriel439** [comment]
You're welcome! 🙂
