### ISSUE TITLE
Labels of records should be quoted in YAML

### ISSUE THREAD

**Issue by markus1189** [dhall-lang/dhall-json#41]
When translating a record to YAML, the labels should always be quoted.

Otherwise you can run into bugs like this:

```
$ echo '{ true = "this is true"} ' | dhall-to-yaml
true: this is true
```

which is wrong because `true` is now an actual boolean.  Intead it should quote the label:

```
"true": this is true
```

**Comment by Gabriel439** [comment]
I think you should open an issue against the upstream `yaml` library: https://github.com/snoyberg/yaml/issues

That's the library that `dhall` uses and as far as I can tell it does not provide an option to emit quoted labels when rendering to YAML

**Comment by markus1189** [comment]
Closed in favor if https://github.com/snoyberg/yaml/issues/137
