### ISSUE TITLE
nested association lists were not converted to maps

### ISSUE THREAD

**Issue by semio** [dhall-lang/dhall-json#48]
`dhall-to-json` doesn't work when we supply an association list where the `mapValue` itself is an association list. For example 

```
[ { mapKey = "somekey", mapValue = [ { mapKey = "\$gt", mapValue = 100 } ] } ]
```

was converted to

```json
{
  "somekey": [
    {
      "mapKey": "$gt",
      "mapValue": 100
    }
  ]
}
```

but I guess the expected output should be:

```json
{
  "somekey": {
    "$gt": 100
  }
}
```

Is it possible to make the conversion recursive so that it would generate the expected result? I am new to dhall (and Haskell) so please correct me if I am wrong.

**Comment by Gabriel439** [comment]
@semio: Yes, this is fixable to behave the way you expect.  Let me take a stab at it
