### ISSUE TITLE
Create the .travis.yml file with a dhall definition

### ISSUE THREAD

**Issue by tcoopman** [dhall-lang/dhall-json#54]
I'm looking into dhall to build configuration files for gitlab and maybe kubernetes, so was looking into the repository a bit, and I was wondering if it would be a nice showcase/example to have your `.travis` file build with dhall?

**Comment by Gabriel439** [comment]
Yeah, this a great idea!  Note that this project doesn't use the `.travis.yml` file any more for CI and I just forgot to remove the file, but I can still keep the `.travis.yml` file around in the `./examples` directory for the purposes of this example.
