### ISSUE TITLE
Sort in record not supported ?

### ISSUE THREAD

**Issue by haitlahcen** [dhall-lang/dhall-json#70]
[Dhall `1.18`](https://github.com/dhall-lang/dhall-haskell/releases/tag/1.18.0) introduced kind-polymorphism thanks to a `Sort` constant above `Kind`.

Generating `yaml|json` from a value annotated by fixing a `Sort` contained by a record throws an error

**`test.dhall`**
```
    let A = { X = { a : Text }, Y = λ(K : Type) → { a : K } }

in  { a = 1 } : A.Y Natural
```
**`dhall <<< ./test.dhall`**
```
{ a = 1 }
```
**`dhall-to-yaml <<< ./test.dhall`**
```
Error: Invalid field type

{ X = { a : Text }, Y = λ(K : Type) → { a : K } }
```

Extracting `Y` from `A` make the above command working.
Am I missing something or this behavior was not expected ?

**Comment by Gabriel439** [comment]
@haitlahcen: I think you might be using a version of `dhall-to-yaml` that was built against an older version of `dhall`.  The example you gave works for me for both `dhall-1.18` and `dhall-json-1.2.4`:

```bash
$ dhall <<< './example.dhall' 
{ a = 1 }

$ dhall-to-yaml <<< './example.dhall' 
a: 1
```

**Comment by haitlahcen** [comment]
I just noticed that my build through nix was not for the latest, was running dhall-json 1.2.3, sorry for that ^^

**Comment by Gabriel439** [comment]
@haitlahcen: No worries at all :slightly_smiling_face:
