### ISSUE TITLE
Binary Releases?

### ISSUE THREAD

**Issue by joneshf** [dhall-lang/dhall-json#8]
I'd love to be able to use `dhall-to-json` and `dhall-to-yaml` in places where the Haskell or nix toolchain is not set up. We could build binaries on travis for OSX and linux, then uploading them through GitHub Releases. It would allow people to use these binaries whether or not they have Haskell or nix setup (or are restricted from that for whatever reason).

@Gabriel439 Would you be interested in a PR for that?

**Comment by Gabriel439** [comment]
Yes, I'm very much interested in supporting that and would welcome the PR.  Let me know if you need any help from me to do that

**Comment by joneshf** [comment]
Fixed by #9 and #11
